### ISSUE TITLE
Other VPNs

### ISSUE THREAD

**Issue by maniksejwal** [pratyaksh123/IITJ_Auth#4]
**Is your feature request related to a problem? Please describe.**
IITJ auth doesn't help me when I visit AIIMS. Their login page doesn't works slightly

**Describe the solution you'd like**
Ability to login into multiple VPNs/firewalls

**Describe alternatives you've considered**
NA

**Additional context**
Later

**Comment by pratyaksh123** [comment]
@maniksejwal Yeah, the current logic will work until it makes that authenticate() call in the network callBack, after then it's very specific to the IITJ's captive portal page. I think doing this for some other VPN is quite easy, just see what your captive portal looks like and decide what to do next ( which is quite similar to what is being done now ). Unfortunately, I can't do this until I have access to AIIMS wifi.

**Comment by maniksejwal** [comment]
You can give me the details of information that you require

**Comment by pratyaksh123** [comment]
Sorry, I might not be able to see this rn, feel free to go through the code, it's basically a foreground service that has a Network callback that listens for a wifi network with a captive portal. Now it's just a matter of how you capture required inputs from the user and make the request to the captive portal.
